name: Autograding Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  Unit-Tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.0.2"
    - name: Build
      run: swift build
    - name: Run unit tests
      run: swift test
SwiftFormat:
  runs-on: macos-latest
  steps:
    - uses: actions/checkout@v4
    - name: SwiftFormat
      run: swiftformat --lint . --strict --reporter github-actions-log